// Variables used with clickChange

let architectureTitle1 = "Sentosa-Brani Masterplan - WilkinsonEyre"
let architectureTitle2 = "Shenzhen Bay Avenue East Extension - WilkinsonEyre"
let architectureTitle3 = "HKIA Sky Bridge - WilkinsonEyre"
let architectureTitle4 = "Healex House: Phase 2, Esher - Clive Chapman Architect"
let architectureTitle5 = "New Road, Esher - Clive Chapman Architect"

let architecturePara1a = "WilkinsonEyre and Grant Associates, alongside a multidisciplinary team are working on plans for a major conceptual masterplan to reinvent the Singaporean islands of Sentosa and Pulau Brani as a global leisure and recreation destination, set within a biodiverse tropical landscape."
let architecturePara2a = "WilkinsonEyre has won a major international competition for the urban design and masterplanning of the Greater Bay area of Shenzhen, southeastern China. Commissioned by the Shenzhen Government, the Shenzhen Bay Avenue East Extension will create a 1km multi-layered pedestrian connection between the commercial district of the city and the bay, introducing a lively public realm promoting healthy and sustainable living."
let architecturePara3a = "The main structure of Sky Bridge at Hong Kong International Airport (HKIA) has been successfully delivered to its final position, concluding the prefabrication phase of the construction programme to mark an important project milestone. The 200m long Sky Bridge at Hong Kong International Airport will directly connect Terminal 1 with the North Satellite Concourse, and is anticipated to be the world's longest airside bridge."
let architecturePara4a = "Following the successful completion of a major refurbishment and extension to their existing HQ in 2011, CCA have been appointed to provide a scheme to accommodate growing numbers of staff at Healix International, on the prominent corner of Esher Green and High St."
let architecturePara5a = "A new application for the site to the rear of No.12, new Road Esher. The site is currently an underutilised amenity space, including a dilapidated private tennis court and freestanding garage. The proposals seek to demolish an existing garage and provide one, four-bedroom residential house (Use Class C3(a)), together with associated parking, gardens and additional landscaping."

let architecturePara1b = "Known as the Sentosa-Brani masterplan, the comprehensive blueprint for re-imagining the islands will be rolled out in phases over the next two to three decades. The redeveloped islands will feature five distinct zones - Vibrant Cluster, Island Heart, Waterfront, Ridgeline and Beachfront. Each will deliver unique experiences, with the zones progressively taking on a more leisurely and naturalistic character as visitors travel further from the urban heartlands towards the islands' edges."
let architecturePara2b = "Key urban spaces include a transport interchange with a bus station and links to two subway stations, a sunken plaza and the Platform Park, envisaged as a calm space amid the hustle and bustle of the city."
let architecturePara3b = "Three precast segments were transported to the assembly yard in the midfield area of HKIA from September to October 2019. The segments were then assembled to form the main structure of the bridge and the main structure of the bridge, weighing over 5000 tonnes, was transported over 3km on HKIA's apron from the assembly yard to the bridge's final position."
let architecturePara4b = "The proposals seek to provide 1530m2 of Grade A office space over 4 storeys as well as retaining 280m2 of retail use on the ground floor. The proposed replacement building positively addresses and marks the junction, providing more active street edges, enhancing the local townscape, as well as views from the neighbouring conservation area."
let architecturePara5b = "The new dwelling has been designed to respond to the scale and sitting of the existing building, whilst respecting the neighbouring properties, their gardens and the established landscaping around the perimeter of the site."
